### ISSUE TITLE
Sendgrid mails goes to spam folder

### ISSUE THREAD

**Issue by CryptorClub** [eemebarbe/schemeBeam#15]
Sendgrid mails goes to spam folder and their support propose only get Dedicated IP.
Part of their mail:
> It is also important to note that you are on a Shared IP, there is some risk involved as other users use the same sending IP address to deliver their email as well. SendGrid does its best to identify bad senders in our system but unfortunately one or two bad senders on Shared IPs can sometimes impact the email deliverability of good senders.
> 
> What I can recommend in this case is encourage those recipients (or move your test emails) out of the spam folder and into the inbox. the more this happens the more your reputation will build as it is just starting out fresh sending with us.

I've setup DKIM and SPF records on my domain... Anyway I live theory, thats probably its not 100% their problem.
Mayby also mail template is too popular, and gmail automaticaly recognize it as spam. 

How about your mails @eemebarbe ?
P.S. thanks for answer on previous issue.

**Comment by eemebarbe** [comment]
That wouldn't have anything to do with the app.

**Comment by CryptorClub** [comment]
I understand it completely. How about your mails on your server, does it delivers in incoming box?
