### ISSUE TITLE
Is this package active? 

### ISSUE THREAD

**Issue by elie222** [eemebarbe/schemeBeam#3]
Love the concept. Wanted to build something like this ourselves but would rather contribute to a working project instead of recreating the wheel. Is this package in a stable state?

**Comment by eemebarbe** [comment]
I do plan on switching over to React-Router V4 and continuing to build on this some time in the future. I'm not sure if updating packages would have any breaking changes, however the project isn't incredibly huge and I'm sure it wouldn't take much to fix if that were the case. If you do end up trying, feel free to contact me for troubleshooting. If not, I'll likely be updating everything in the near(-ish) future, as I'll need this tool for my own uses.

**Comment by elie222** [comment]
Cool. Sounds great. I cloned it earlier today and will get it running
shortly. I saw there wasn't too much code.

React 16 is another possible update. The breaking change being things like
prop types, but very manageable to update.

**Comment by eemebarbe** [comment]
Cool. Thanks for your interest in the project!
