### ISSUE TITLE
Issues running on localhost

### ISSUE THREAD

**Issue by elie222** [eemebarbe/schemeBeam#4]
This doesn't seem to run great on localhost. The emails don't come through with the link. I had to read the actual message to find and verify my registration.

Also, after that when going to my referral link:
http://localhost:8000/#/c2c=a9844f7d2539b642655b2401feee8

I got this error message:
`Not a valid referral link!`

**Comment by eemebarbe** [comment]
Don't come through with the link? What do you mean? Try checking your spam folder. In addition, Sendgrid takes some time to send the messages out if you're using a free account.

You have to receive the registration email and verify it in order to activate the referral link.
